// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2cOCqTX8lmJixacU1J25ja3VLq_yJ8WU',
    appId: '1:883694809918:web:754fc3fb9fe14baf5bb26f',
    messagingSenderId: '883694809918',
    projectId: 'fruit-hub-bd5e0',
    authDomain: 'fruit-hub-bd5e0.firebaseapp.com',
    storageBucket: 'fruit-hub-bd5e0.firebasestorage.app',
    measurementId: 'G-7QGD9Z6QTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXynjBYSoftpYvuW5ELxGmoXxAZR9SNo',
    appId: '1:883694809918:android:b2e4d2b8f51b11465bb26f',
    messagingSenderId: '883694809918',
    projectId: 'fruit-hub-bd5e0',
    storageBucket: 'fruit-hub-bd5e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDoVcT44XuQpPNSVm16eCUn-PRgX1JhE8',
    appId: '1:883694809918:ios:e1cfbff51ae26e7b5bb26f',
    messagingSenderId: '883694809918',
    projectId: 'fruit-hub-bd5e0',
    storageBucket: 'fruit-hub-bd5e0.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDoVcT44XuQpPNSVm16eCUn-PRgX1JhE8',
    appId: '1:883694809918:ios:e1cfbff51ae26e7b5bb26f',
    messagingSenderId: '883694809918',
    projectId: 'fruit-hub-bd5e0',
    storageBucket: 'fruit-hub-bd5e0.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2cOCqTX8lmJixacU1J25ja3VLq_yJ8WU',
    appId: '1:883694809918:web:c1bf0f10321c46375bb26f',
    messagingSenderId: '883694809918',
    projectId: 'fruit-hub-bd5e0',
    authDomain: 'fruit-hub-bd5e0.firebaseapp.com',
    storageBucket: 'fruit-hub-bd5e0.firebasestorage.app',
    measurementId: 'G-5QBQB9BECM',
  );
}
